'use client';
import {useState} from 'react';
import {RECIPES,recipeState,craft} from './crafting.mjs';
import {ITEMS,CAPACITY} from './engine.mjs';
import {Localized} from './i18n';
import ItemIcon from './ItemIcon';
export default function CraftingPanel({game}:{game:any}){
 const [selected,setSelected]=useState('bandages'),[done,setDone]=useState(false);const state=recipeState(game,selected)!,r=state.recipe;
 const cells=state.ingredients.flatMap(i=>Array.from({length:i.need},()=>i));
 return <Localized><div className="craft-workbench"><p>Use supplies from your backpack. Worn equipment must be unequipped first. Tools are kept.</p><div className="craft-layout"><div className="craft-recipes" role="group" aria-label="Crafting recipes">{RECIPES.map(recipe=>{const s=recipeState(game,recipe.id)!;return <button key={recipe.id} aria-pressed={recipe.id===selected} onClick={()=>{setSelected(recipe.id);setDone(false)}}><ItemIcon id={recipe.output} size={20}/><span>{recipe.name}<small>{s.ready?'Ready to craft':'Materials needed'}</small></span><b>{recipe.quantity>1?'x'+recipe.quantity:''}</b></button>})}</div><section className="craft-detail"><h3>{r.name}</h3><div className="craft-process"><div className="craft-grid">{Array.from({length:9},(_,i)=><div key={i} className={cells[i]&&cells[i].have<cells[i].need?'missing':''}>{cells[i]&&<ItemIcon id={cells[i].item} size={21}/>}</div>)}</div><span aria-hidden="true">→</span><div className="craft-result"><ItemIcon id={r.output} size={28}/><strong>x{r.quantity}</strong></div></div><strong>{ITEMS[r.output as keyof typeof ITEMS].name}</strong><p>{ITEMS[r.output as keyof typeof ITEMS].desc}</p><ul className="craft-materials">{state.ingredients.map(i=><li key={i.item} className={i.have>=i.need?'available':'missing'}><span>{ITEMS[i.item as keyof typeof ITEMS].name}</span><b>{i.have} / {i.need}</b></li>)}</ul>{r.tool&&<div className="craft-tool"><ItemIcon id={r.tool} size={16}/><span>Required tool · kept</span><strong>{state.hasTool?'Available':'Missing'}</strong></div>}<p>Resulting carry weight: {Math.max(0,state.weight).toFixed(1)} / {CAPACITY} kg</p><button className="primary-btn" disabled={!state.ready} onClick={()=>setDone(craft(game,selected))}>Craft item</button><p role="status">{done?'Crafted item placed in your backpack.':!state.active?'Enter the sector to craft.':!state.hasTool?'Find a toolbox in vehicles or storage.':state.ingredients.some(i=>i.have<i.need)?'Collect the missing materials.':state.weight>CAPACITY?'Not enough carrying capacity.':'Ready to craft'}</p></section></div></div></Localized>;
}
