'use client';
import { useEffect, useRef, useState } from 'react';
import dynamic from 'next/dynamic';
import { Biohazard, ArrowUpRight, ArrowRight, Backpack, Battery, Check, CheckCheck, ChevronRight, CircleHelp, Crosshair, Scan, Droplet, Footprints, Heart, KeyRound, LockKeyhole, MapPin, Maximize2, Minus, Package, Pause, Play, Plus, Radio, RotateCcw, Shield, Skull, Volume2, VolumeX, Wrench, Zap, X, FlaskConical, DoorOpen, MousePointer2, Circle, Eye, Wine, Utensils, Armchair } from 'lucide-react';
import { Dialog, DialogContent, DialogDescription, DialogTitle } from '@/components/ui/dialog';
import { Progress } from '@/components/ui/progress';
import { Game, ITEMS, CAPACITY, LEVELS } from './engine.mjs';
import { ART, ART_CELLS } from './art';
import InventoryDialog from './InventoryDialog';
import { DEFAULT_ZOOM, MIN_ZOOM, MAX_ZOOM, clampZoom } from './camera-settings.mjs';
const Scene=dynamic(()=>import('./Scene'),{ssr:false,loading:()=> <div className="loading-scene"><Biohazard/><span>SEKTOR WIRD ERKUNDET</span></div>});
const icons:any={crowbar:Wrench,medkit:Plus,bottle:Wine,fuse:Zap,fuel:Droplet,keycard:KeyRound,sample:FlaskConical,battery:Battery,scrap:Package,chair:Armchair,tire:Circle,toolbox:Wrench,ration:Utensils};
const ItemIcon=({id,size=20}:{id:string,size?:number})=>{if(id in ART_CELLS)return <img className="item-art" src={`${ART.icons}${id}.webp`} alt="" width={size*2} height={size*1.5} draggable={false}/>;const Icon=icons[id]||Package;return <Icon size={size} strokeWidth={1.6}/>};
const formatTime=(time:number)=>`${Math.floor(time/60).toString().padStart(2,'0')}:${Math.floor(time%60).toString().padStart(2,'0')}`;
export default function GameClient(){
 const [game]=useState<any>(()=>new Game());const [,refresh]=useState(0);const [hover,setHover]=useState<any>(null);const [inventoryItem,setInventoryItem]=useState<string|null>(null);const [help,setHelp]=useState(false);const [confirmRestart,setConfirmRestart]=useState(false);const [zoom,setZoom]=useState(DEFAULT_ZOOM);const [viewReset,setViewReset]=useState(0);const [sound,setSound]=useState(false);const [fullscreen,setFullscreen]=useState(false);const shell=useRef<HTMLDivElement>(null);const audio=useRef<any>(null);const lastSound=useRef('');
 useEffect(()=>game.subscribe(()=>refresh(n=>n+1)),[game]);
 useEffect(()=>{const onVisibility=()=>{if(document.hidden){if(game.inventoryOpen&&game.inventoryReturnMode==='playing'){game.inventoryReturnMode='paused';game.emit()}else if(game.mode==='playing')game.pause()}};document.addEventListener('visibilitychange',onVisibility);return()=>document.removeEventListener('visibilitychange',onVisibility)},[game]);
 useEffect(()=>{const key=(e:KeyboardEvent)=>{
  if(e.ctrlKey||e.metaKey||e.altKey)return;
  const target=e.target as HTMLElement;
  if(game.inventoryOpen){if(e.key.toLowerCase()==='i'||e.key==='Escape'){e.preventDefault();e.stopPropagation();if(!e.repeat)game.closeInventory()}return;}
  if(help||confirmRestart||target?.isContentEditable||['INPUT','TEXTAREA','SELECT'].includes(target?.tagName))return;
  if(e.key.toLowerCase()==='i'){e.preventDefault();e.stopPropagation();if(!e.repeat)game.openInventory();return;}
  if(e.key===' '&&target?.closest('button'))return;
  if([' ','Escape','1','2','3','Shift'].includes(e.key))e.preventDefault();
  if(e.repeat)return;
  if(e.key===' '||e.key==='Escape'){if(game.throwing){game.throwing=false;game.emit()}else game.pause()}
  else if(e.key==='2')game.use('medkit');else if(e.key==='3')game.use('bottle');else if(e.key==='1')game.use('crowbar');else if(e.key==='Shift'&&game.mode==='playing'){game.sneak=!game.sneak;game.emit()}
 };window.addEventListener('keydown',key,true);return()=>window.removeEventListener('keydown',key,true)},[game,help,confirmRestart]);
 useEffect(()=>{const f=()=>setFullscreen(!!document.fullscreenElement);document.addEventListener('fullscreenchange',f);return()=>document.removeEventListener('fullscreenchange',f)},[]);
 useEffect(()=>{if(!sound)return;const latest=game.history[0];if(!latest||lastSound.current===latest.id||!audio.current)return;lastSound.current=latest.id;const ctx=audio.current;const oscillator=ctx.createOscillator(),gain=ctx.createGain();oscillator.type='sine';oscillator.frequency.setValueAtTime(latest.tone==='warn'?180:latest.tone==='success'?620:380,ctx.currentTime);oscillator.frequency.exponentialRampToValueAtTime(110,ctx.currentTime+.1);gain.gain.setValueAtTime(.035,ctx.currentTime);gain.gain.exponentialRampToValueAtTime(.001,ctx.currentTime+.16);oscillator.connect(gain).connect(ctx.destination);oscillator.start();oscillator.stop(ctx.currentTime+.17)},[sound,game.history[0]?.id]);
 const toggleSound=()=>{if(!audio.current)audio.current=new (window.AudioContext||(window as any).webkitAudioContext)();audio.current.resume();setSound(!sound)};
 const toggleHelp=()=>{if(game.mode==='playing')game.pause();setHelp(true)};
 const requestRestart=()=>{if(game.mode==='playing')game.pause();setConfirmRestart(true)};
 const full=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await shell.current?.requestFullscreen()}catch{game.log('Vollbild ist in diesem Fenster nicht verfügbar.')}};
 const resetView=()=>{setZoom(DEFAULT_ZOOM);setViewReset(n=>n+1)};
 const goals=game.objectives();const entity=game.selected||hover;const invIds=[...new Set<string>(game.inventory)];const selectedDef=inventoryItem?(ITEMS as any)[inventoryItem]:null;
 const isStopped=game.mode!=='playing';const command=(id:string)=>{setInventoryItem(id);game.use(id)};
 return <div className={`game-shell sector-theme-${game.level}`} ref={shell}>
  <header className="topbar">
   <a className="brand" href="#" onClick={e=>e.preventDefault()} aria-label="Ashfall Dead Sector"><span className="brand-symbol"><Biohazard size={28}/></span><span><strong>ASHFALL<span className="brand-dot">.</span></strong><small>DEAD SECTOR</small></span></a>
   <div className="world-clock"><span className="live-dot"/> TAG 1.247 <span className="divider">/</span> 06:42 <span className="weather">{game.data.weather}</span></div>
   <div className="top-actions"><button className="inventory-toggle" onClick={()=>game.openInventory()} aria-label="Inventar öffnen" title="Inventar öffnen (I)"><Backpack size={19}/><span>INVENTAR</span><kbd>I</kbd></button><button onClick={toggleSound} className={sound?'icon-btn active':'icon-btn'} title={sound?'Ton ausschalten':'Ton einschalten'} aria-label={sound?'Ton ausschalten':'Ton einschalten'}>{sound?<Volume2 size={18}/>:<VolumeX size={18}/>}</button><button className="icon-btn" onClick={toggleHelp} title="Steuerung und Hilfe" aria-label="Steuerung und Hilfe"><CircleHelp size={18}/></button><span className="action-divider"/><button className="pause-btn" onClick={()=>game.mode==='briefing'?game.start():game.pause()} disabled={['dead','complete','won'].includes(game.mode)}>{game.mode==='playing'?<Pause size={15}/>:<Play size={15}/>}<span>{game.mode==='playing'?'PAUSE':game.mode==='briefing'?'STARTEN':'WEITER'}</span><kbd>␣</kbd></button></div>
  </header>
  <div className="campaign-bar"><div className="campaign-label"><span>KAMPAGNE</span><strong>Der letzte Ausweg</strong></div><ol className="chapters">{LEVELS.map((l:any,i:number)=><li key={l.name} className={game.level===i?'chapter current':game.unlocked>i?'chapter finished':'chapter locked'}><span className="chapter-number">{game.unlocked>i?<Check size={15}/>:String(i+1).padStart(2,'0')}</span><div><small>{i===2?'FINALE':`KAPITEL ${i+1}`}</small><span>{l.name}</span></div>{i>game.unlocked&&<LockKeyhole size={13} className="chapter-lock"/>}{i<2&&<ChevronRight className="chapter-arrow" size={18}/>}</li>)}</ol><div className="campaign-count">0{game.level+1}<span> / 03</span></div></div>
  <main className="play-layout">
   <section className={`playfield ${game.flash>.1?'damage-flash':''}`} aria-label="Spielwelt">
    <Scene game={game} onHover={setHover} zoom={zoom} onZoomChange={setZoom} viewReset={viewReset}/>
    <div className="scene-vignette"/>
    <div className="sector-heading"><div className="eyebrow"><span className="orange-dash"/>{game.data.tag}</div><h1>{game.data.place}</h1><p><MapPin size={12}/> {game.level===0?'52° 31′ N · 13° 24′ E':game.level===1?'28 M UNTER DER OBERFLÄCHE':'LETZTE BEKANNTE LANDEZONE'}</p></div>
    <div className="scene-status"><span className={game.mode==='playing'?'status-dot live':'status-dot'}/>{game.mode==='playing'?'EINSATZ AKTIV':game.mode==='paused'?'PAUSIERT':game.mode==='briefing'?'BEREIT ZUM EINSATZ':game.mode==='dead'?'SIGNAL VERLOREN':'SEKTOR GESICHERT'}</div>
    {game.level===2&&game.signal>=0&&<div className={`evac-timer ${game.signal===0?'ready':''}`}><Radio size={20}/><span>{game.signal===0?'EVAKUIERUNG BEREIT':'EVAKUIERUNG IN'}</span><strong>{game.signal===0?<CheckCheck size={24}/>:formatTime(Math.ceil(game.signal))}</strong></div>}
    <div className="map-south"><div className="scene-coordinates">S-{String(game.level+1).padStart(2,'0')} <span>·</span> X {game.player.x.toFixed(1)} <span>/</span> Y {game.player.y.toFixed(1)}</div><div className="zoom-tools" role="group" aria-label="Kartenzoom"><small>ZOOM</small><button className="icon-btn" onClick={()=>setZoom(z=>clampZoom(z/1.2))} disabled={zoom<=MIN_ZOOM+.001} aria-label="Herauszoomen" title="Herauszoomen (−)"><Minus size={19}/></button><output aria-label="Zoomstufe">{Math.round(zoom*100)}%</output><button className="icon-btn" onClick={()=>setZoom(z=>clampZoom(z*1.2))} disabled={zoom>=MAX_ZOOM-.001} aria-label="Hineinzoomen" title="Hineinzoomen (+)"><Plus size={19}/></button><button className="icon-btn zoom-reset" onClick={resetView} aria-label="Ganze Karte anzeigen" title="Ganze Karte anzeigen (0)"><Scan size={17}/><span>Übersicht</span></button><button className="icon-btn" onClick={full} aria-label={fullscreen?'Vollbild verlassen':'Vollbild'} title={fullscreen?'Vollbild verlassen':'Vollbild'}><Maximize2 size={17}/></button></div></div>
    <div className="minimap"><span>N <span>↑</span></span><svg viewBox="-1 -1 23 21" role="img" aria-label="Übersicht des Sektors"><rect x="-.5" y="-.5" width="21" height="19" fill="#233b32"/>{game.entities.filter((e:any)=>!e.removed).map((e:any)=><rect key={e.id} x={e.x-.25} y={e.y-.25} width={e.w||.5} height={e.h||.5} fill={e.type==='prop'?'#647363':e.type==='exit'?'#edbb78':e.type==='item'?'#b1be8f':'#8b9d7b'}/>)}{game.zombies.filter((z:any)=>z.hp>0).map((z:any)=><circle key={z.id} cx={z.x} cy={z.y} r=".35" fill="#d78c68"/>)}<circle cx={game.player.x} cy={game.player.y} r=".55" fill="#ffe2a2"/><circle cx={game.player.x} cy={game.player.y} r="1.25" fill="none" stroke="#ffe2a2" strokeWidth=".12"/></svg><small>SEKTORÜBERSICHT</small></div>
    {game.mode==='playing'&&<>
     <div className="field-feedback" aria-live="polite">{game.history.slice(0,2).map((event:any)=><p className={event.tone} key={event.id}><span/>{event.text}</p>)}</div>
     {game.throwing&&<div className="throw-prompt"><Wine size={18}/><span>Wurfziel wählen <small>Max. 9 Felder · ESC zum Abbrechen</small></span><button onClick={()=>{game.throwing=false;game.emit()}} aria-label="Wurf abbrechen"><X size={17}/></button></div>}
     {entity&&!game.throwing&&<div className="entity-card"><span className={`entity-icon ${entity.type==='zombie'?'danger':''}`}>{entity.type==='item'?<ItemIcon id={entity.item}/>:entity.type==='zombie'?<ItemIcon id="zombie"/>:entity.type==='exit'||entity.type==='door'?<DoorOpen/>:entity.type==='generator'?<Zap/>:<Eye/>}</span><div><small>{entity.type==='item'?`${(ITEMS as any)[entity.item].weight.toFixed(1)} KG · AUFHEBEN`:entity.type==='zombie'?`${Math.ceil(entity.hp)} / ${entity.maxHp} · ANGREIFEN`:entity.type==='prop'?'UNTERSUCHEN':entity.type==='container'&&entity.open&&!entity.contents.length?'LEER · DURCHSUCHT':'INTERAGIEREN'}</small><strong>{entity.name}</strong><p>{entity.desc}</p></div>{entity.type!=='prop'&&<button aria-label={`Mit ${entity.name} interagieren`} onClick={()=>game.select(entity.id)}><ArrowUpRight size={22}/></button>}</div>}
    </>}
    {game.mode==='briefing'&&<div className="briefing-card"><div className="briefing-scene"><img src={ART.sectors[game.level].src} alt={ART.sectors[game.level].alt}/><span>SEKTOR 0{game.level+1}</span></div><div className="briefing-kicker"><Radio size={15}/> EINGEHENDER FUNKSPRUCH <span>0{game.level+1}</span></div><h2>{game.data.name}</h2><p>{game.data.intro}</p><div className="briefing-tip"><MousePointer2 size={17}/><span>Klicke auf den Boden, um zu gehen.<br/>Klicke auf Objekte, um sie zu untersuchen.</span></div><button className="primary-btn" onClick={()=>game.start()}>SEKTOR BETRETEN <ArrowRight size={17}/></button></div>}
    {game.mode==='paused'&&!game.inventoryOpen&&<div className="state-overlay"><div className="state-card"><Pause size={26} className="state-icon"/><span className="eyebrow">EIN MOMENT STILLE</span><h2>Einsatz pausiert.</h2><p>Atme durch. Hier läuft dir nichts davon.</p><button className="primary-btn" onClick={()=>game.start()}>WEITERSPIELEN <Play size={15}/></button><button className="text-btn" onClick={requestRestart}><RotateCcw size={14}/> Sektor neu starten</button></div></div>}
    {['complete','won','dead'].includes(game.mode)&&<div className="state-overlay"><div className={`state-card end-card ${game.mode==='dead'?'death':''}`}>
     {game.mode==='dead'?<img className="end-portrait" src="/images/openart/icons/zombie.webp" alt=""/>:game.mode==='won'?<Radio className="state-icon" size={38}/>:<DoorOpen className="state-icon" size={38}/>}
     <span className="eyebrow">{game.mode==='dead'?'SIGNAL ABGEBROCHEN':game.mode==='won'?'KAMPAGNE ABGESCHLOSSEN':'KAPITEL ABGESCHLOSSEN'}</span><h2>{game.mode==='dead'?'Die Stadt hat dich.':game.mode==='won'?'Ein Morgen bleibt.':'Du bist noch hier.'}</h2><p>{game.mode==='dead'?'Deine Ausrüstung vom Sektorbeginn wartet auf dich. Nutze Verbände und bleib in Bewegung.':game.mode==='won'?'Die Rotoren übertönen die Stadt. Du und Probe N-04 seid in Sicherheit. Drei Sektoren. Eine zweite Chance.':game.level===0?'Das Bunkertor öffnet sich. Aus der Dunkelheit kommt ein Geräusch.':'Die Probe ist gesichert. Auf dem Dach wartet deine letzte Chance.'}</p>
     <div className="end-stats"><span><strong>{game.kills}</strong>INFIZIERTE</span><span><strong>{formatTime(game.totalTime)}</strong>EINSATZZEIT</span><span><strong>{Math.ceil(game.health)}%</strong>GESUNDHEIT</span></div>
     <button className="primary-btn" onClick={()=>game.mode==='complete'?game.next():game.mode==='dead'?game.restart():game.newGame()}>{game.mode==='complete'?'NÄCHSTEN SEKTOR BETRETEN':game.mode==='dead'?'SEKTOR ERNEUT VERSUCHEN':'NEUE KAMPAGNE'}<ArrowRight size={17}/></button>
    </div></div>}
    <div className="quickbar"><div className="quickslots">
     <button className="quickslot equipped" onClick={()=>command('crowbar')} disabled={isStopped} title="Brecheisen – automatischer Nahkampf in Reichweite"><kbd>1</kbd><ItemIcon id="crowbar" size={25}/><span>{game.has('crowbar')?'Brecheisen':'Fäuste'}</span><small>NAHKAMPF</small></button>
     <button className="quickslot" onClick={()=>command('medkit')} disabled={isStopped||!game.has('medkit')} title="Verband benutzen"><kbd>2</kbd><ItemIcon id="medkit" size={25}/><b>{game.count('medkit')}</b><span>Verband</span><small>+40 LP</small></button>
     <button className={`quickslot ${game.throwing?'throwing':''}`} onClick={()=>command('bottle')} disabled={isStopped||!game.has('bottle')} title="Flasche werfen"><kbd>3</kbd><ItemIcon id="bottle" size={25}/><b>{game.count('bottle')}</b><span>Flasche</span><small>ABLENKEN</small></button>
    </div><span className="quick-divider"/><button className={`stealth-btn ${game.sneak?'enabled':''}`} onClick={()=>{game.sneak=!game.sneak;game.emit()}} disabled={isStopped}><Footprints size={20}/><span>{game.sneak?'Schleichen':'Gehen'}<small>SHIFT</small></span><span className="toggle-indicator"/></button></div>
   </section>
   <aside className="sidebar">
    <section className="survivor-section"><div className="panel-label"><span>ÜBERLEBENDE</span><span className="id-label">ID — 007</span></div><div className="survivor"><span className="survivor-avatar"><img src="/images/openart/icons/mara.webp" alt="Mara Voss"/><i/></span><div><h2>Mara Voss</h2><p>{game.health>65?'Stabil. Noch am Leben.':game.health>30?'Verletzt. Zeit für einen Verband.':'Kritisch. Such Deckung.'}</p></div><span className="survivor-level">07</span></div><div className="vital-label"><span><Heart size={13}/> Gesundheit</span><strong>{Math.ceil(game.health)} <small>/ 100</small></strong></div><Progress locale="de-DE" className={`health-progress ${game.health<35?'critical':''}`} value={game.health} aria-label="Gesundheit"/><div className="vital-meta"><span><span className={game.sneak?'noise-dot quiet':'noise-dot'}/>{game.sneak?'LEISE':game.noise>.5?'HÖRBAR':'UNAUFFÄLLIG'}</span><span><Skull size={12}/> {game.kills} AUSGESCHALTET</span></div></section>
    <section className="mission-section"><div className="panel-label"><span>AKTUELLER AUFTRAG</span><Crosshair size={14}/></div><div className="mission-art"><img src={ART.sectors[game.level].src} alt={ART.sectors[game.level].alt}/><div/><span>0{game.level+1} <small>/ 03</small></span><strong>{game.level===0?'Ein Weg nach unten.':game.level===1?'Hoffnung unter Beton.':'Noch ein letzter Ruf.'}</strong></div><ul className="objectives">{game.data.goals.map((goal:string,i:number)=><li key={goal} className={goals[i]?'done':i===goals.findIndex((v:boolean)=>!v)?'next':''}><span className="objective-check">{goals[i]?<Check size={12}/>:i===goals.findIndex((v:boolean)=>!v)?<span/>:null}</span><span>{goal}</span></li>)}</ul><button className="hint-btn" onClick={()=>game.log(game.data.hint,'story')}><Radio size={13}/> Funkspruch wiederholen <ArrowUpRight size={13}/></button></section>
    <section className="inventory-section"><button className="inventory-expand" onClick={()=>game.openInventory()}><Backpack size={17}/> Inventar öffnen <kbd>I</kbd><ArrowUpRight size={17}/></button><div className="panel-label"><span><Backpack size={15}/> RUCKSACK</span><span className={game.weight>12?'weight heavy':'weight'}>{game.weight.toFixed(1)} <small>/ {CAPACITY} KG</small></span></div><Progress locale="de-DE" className="weight-progress" value={game.weight/CAPACITY*100} aria-label="Traglast"/>
     <div className="inventory-grid">{invIds.map(id=><button key={id} onClick={()=>setInventoryItem(inventoryItem===id?null:id)} className={`inventory-tile ${(ITEMS as any)[id].kind==='quest'?'quest-item':''} ${inventoryItem===id?'selected':''}`} aria-label={`${(ITEMS as any)[id].name}, ${game.count(id)} Stück`} title={(ITEMS as any)[id].name}><ItemIcon id={id} size={24}/><span>{(ITEMS as any)[id].name}</span><b>{game.count(id)>1?`×${game.count(id)}`:''}</b>{(ITEMS as any)[id].kind==='quest'&&<i/>}</button>)}{Array.from({length:Math.max(0,6-invIds.length)}).map((_,i)=><div className="inventory-empty" key={i}><Plus size={13}/></div>)}</div>
     {selectedDef&&game.has(inventoryItem)&&<div className="inventory-detail"><div><strong>{selectedDef.name}</strong><span>{selectedDef.weight.toFixed(1)} kg</span></div><p>{selectedDef.desc}</p><div className="inventory-item-actions">{['heal','food','throw'].includes(selectedDef.kind)&&<button disabled={isStopped} onClick={()=>game.use(inventoryItem)}>{selectedDef.kind==='throw'?'Werfen':'Benutzen'}<ArrowUpRight size={13}/></button>}<button disabled={isStopped} onClick={()=>game.drop(inventoryItem)}>Ablegen <ArrowRight size={13}/></button></div></div>}
     {!selectedDef&&<p className="inventory-hint">Gegenstand anklicken, um ihn zu benutzen oder abzulegen.</p>}
    </section>
    <div className="sidebar-footer"><span><span className="live-dot"/> {game.mode==='dead'?'VERBINDUNG VERLOREN':'FREQUENZ 104.8'}</span><button onClick={requestRestart} aria-label="Sektor neu starten" title="Sektor neu starten"><RotateCcw size={14}/></button></div>
   </aside>
  </main>
  <footer className="instruction-strip"><span><MousePointer2 size={13}/><strong>KLICK</strong> Bewegen & interagieren</span><span><Skull size={13}/><strong>KLICK AUF ZOMBIE</strong> Angreifen</span><span><Footprints size={13}/><strong>SHIFT</strong> Schleichen</span><span className="zoom-help"><Plus size={13}/><strong>MAUSRAD / ZWEI FINGER</strong> Zoomen</span><span className="pan-help"><MousePointer2 size={13}/><strong>RECHTS ZIEHEN</strong> Ansicht verschieben</span></footer>
  <InventoryDialog game={game} portalContainer={fullscreen?shell.current:undefined}/>
  <Dialog open={help} onOpenChange={setHelp}><DialogContent className="game-dialog"><DialogTitle>Überleben in Ashfall</DialogTitle><DialogDescription>Drei Sektoren, eine letzte Evakuierung. Alles, was du für den Weg wissen musst.</DialogDescription><div className="help-list"><p><MousePointer2/><span><strong>Klicken statt Tasten drücken</strong>Klicke auf ein freies Feld. Deine Figur findet den Weg. Ein Klick auf einen Gegenstand führt dich dorthin und interagiert automatisch. Halte die rechte Maustaste und ziehe, um die Ansicht zu verschieben.</span></p><p><Plus/><span><strong>Näher ran oder alles im Blick</strong>Mit dem Mausrad oder zwei Fingern auf der Karte zoomst du von 65 bis 320 %. Auf dem Handy verschiebst du die Karte durch Ziehen. Unten rechts findest du Plus, Minus und „Ganze Karte“. Bei aktiver Karte funktionieren auch die Tasten +, − und 0.</span></p><p><Backpack/><span><strong>Mitnehmen, was du tragen kannst</strong>Mit I oder dem Rucksackknopf öffnest du dein Inventar und pausierst den Einsatz. Durchsuche Kisten und sammle lose Dinge. Im Rucksack kannst du Gegenstände verwenden oder ablegen. Die Grenze liegt bei 14 kg.</span></p><p><Skull/><span><strong>Wähle deine Kämpfe</strong>Klicke auf einen Zombie zum Angreifen. In direkter Nähe verteidigt Mara sich automatisch. Mit SHIFT schleichst du leiser und langsamer.</span></p><p><Wine/><span><strong>Ablenken und durchhalten</strong>2 benutzt einen Verband. 3 wählt eine Flasche: Klicke dann ein freies Feld innerhalb von 9 Feldern an. Zombies folgen dem Lärm 8 Sekunden.</span></p><p><DoorOpen/><span><strong>Finde den Weg hinaus</strong>Geräte und Türen sagen dir, was fehlt. Auftragsgegenstände werden beim Interagieren automatisch eingesetzt. Leertaste pausiert.</span></p></div><button className="primary-btn" onClick={()=>{setHelp(false);if(game.mode==='paused')game.start()}}>VERSTANDEN <Check size={16}/></button></DialogContent></Dialog>
  <Dialog open={confirmRestart} onOpenChange={setConfirmRestart}><DialogContent className="game-dialog restart-dialog"><DialogTitle>Sektor neu starten?</DialogTitle><DialogDescription>Du beginnst diesen Sektor mit der Gesundheit und Ausrüstung vom Eintritt erneut. Frühere Kapitel bleiben abgeschlossen.</DialogDescription><div className="restart-actions"><button className="secondary-btn" onClick={()=>setConfirmRestart(false)}>Abbrechen</button><button className="primary-btn" onClick={()=>{setConfirmRestart(false);setInventoryItem(null);game.restart()}}>NEU STARTEN <RotateCcw size={15}/></button></div></DialogContent></Dialog>
 </div>
}
