'use client';
import {shouldShowIntro,markIntroSeen} from './intro-state.mjs';
import IntroCutscene from './IntroCutscene';
import RecordingControl from './RecordingControl';
import CraftingPanel from './CraftingPanel';
import SavePanel from './SavePanel';
import {Save} from 'lucide-react';
import KodaPreview from './KodaPreview';
import { LanguageSwitch, Localized, LanguageProvider, useLanguage } from './i18n';
import { useEffect, useRef, useState } from 'react';
import dynamic from 'next/dynamic';
import { Biohazard, ArrowUpRight, ArrowRight, Backpack, Battery, Check, CheckCheck, ChevronRight, CircleHelp, Crosshair, Scan, Droplet, Footprints, Heart, KeyRound, LockKeyhole, MapPin, Maximize2, Minus, Package, Pause, Play, Plus, Radio, RotateCcw, Shield, Skull, Volume2, VolumeX, Wrench, Zap, X, FlaskConical, DoorOpen, MousePointer2, Circle, Eye, Wine, Utensils, Armchair } from 'lucide-react';
import { Dialog, DialogContent, DialogDescription, DialogTitle } from '@/components/ui/dialog';
import { Progress } from '@/components/ui/progress';
import { Game, ITEMS, CAPACITY, LEVELS } from './engine.mjs';
import { ART } from './art';
import InventoryDialog from './InventoryDialog';
import ItemIcon from './ItemIcon';
import TutorialPanel from './TutorialPanel';
import RadioPanel from './RadioPanel';
import ScrollRegion from './ScrollRegion';
import { GameAudio, type AudioStatus, type RadioCue } from './GameAudio';
import { tutorialTarget } from './tutorial.mjs';
import { DEFAULT_ZOOM, INITIAL_ZOOM, MIN_ZOOM, MAX_ZOOM, clampZoom } from './camera-settings.mjs';
const Scene=dynamic(()=>import('./Scene'),{ssr:false,loading:()=> <div className="loading-scene"><Biohazard/><span>SCOUTING SECTOR</span></div>});
const formatTime=(time:number)=>`${Math.floor(time/60).toString().padStart(2,'0')}:${Math.floor(time%60).toString().padStart(2,'0')}`;
function GameClient(){
 const {language,setLanguage}=useLanguage();
 const [introOpen,setIntroOpen]=useState<boolean|null>(null);
 useEffect(()=>{try{setIntroOpen(shouldShowIntro(localStorage))}catch{setIntroOpen(true)}},[]);
 const [game]=useState<any>(()=>new Game({tutorial:true}));const [,refresh]=useState(0);const [hover,setHover]=useState<any>(null);const [inventoryItem,setInventoryItem]=useState<string|null>(null);const [help,setHelp]=useState(false);const [panel,setPanel]=useState<'mission'|'radio'|'save'|'craft'|null>(null);const panelWasPlaying=useRef(false);const [confirmRestart,setConfirmRestart]=useState(false);const [zoom,setZoom]=useState(INITIAL_ZOOM);const [viewReset,setViewReset]=useState(0);const [rotation,setRotation]=useState(0);const [following,setFollowing]=useState(true);const [sound,setSound]=useState(false);const [fullscreen,setFullscreen]=useState(false);const shell=useRef<HTMLDivElement>(null);const audio=useRef<GameAudio|null>(null);const audioChoice=useRef(false);const [audioStatus,setAudioStatus]=useState<AudioStatus>({cue:null,playing:false,loading:false,error:null});const [musicLevel,setMusicLevel]=useState(.38);const [voiceLevel,setVoiceLevel]=useState(.85);
 useEffect(()=>{game.language=language;game.emit()},[game,language]);
 useEffect(()=>game.subscribe(()=>refresh(n=>n+1)),[game]);
 useEffect(()=>{const onVisibility=()=>{if(document.hidden){if((game.inventoryOpen||game.lootOpen)&&game.inventoryReturnMode==='playing'){game.inventoryReturnMode='paused';game.emit()}else if(game.mode==='playing')game.pause()}};document.addEventListener('visibilitychange',onVisibility);return()=>document.removeEventListener('visibilitychange',onVisibility)},[game]);
 useEffect(()=>{const key=(e:KeyboardEvent)=>{
  if(introOpen||game.level===2&&game.mode==='complete'||e.ctrlKey||e.metaKey||e.altKey)return;
  const target=e.target as HTMLElement;
  if(game.companionOpen){if(e.key==='Escape'){e.preventDefault();game.closeCompanion()}return;}
  if(game.inventoryOpen||game.lootOpen){if(e.key.toLowerCase()==='i'||e.key==='Escape'){e.preventDefault();e.stopPropagation();if(!e.repeat)game.closeInventory()}return;}
  if(help||panel||confirmRestart||target?.isContentEditable||['INPUT','TEXTAREA','SELECT'].includes(target?.tagName))return;
  if(e.key.toLowerCase()==='i'){e.preventDefault();e.stopPropagation();if(!e.repeat)game.openInventory();return;}
  if(e.key==='Escape'&&game.tutorial.reading&&game.mode==='playing'){e.preventDefault();e.stopPropagation();game.acknowledgeTutorial();return;}
  if(e.key===' '&&target?.closest('button'))return;
  if([' ','Escape','1','2','3','Shift'].includes(e.key))e.preventDefault();
  if(e.repeat)return;
  if(e.key===' '||e.key==='Escape'){if(game.throwing){game.throwing=false;game.emit()}else game.pause()}
  else if(e.key==='2')game.use('medkit');else if(e.key==='3')game.use('bottle');else if(e.key==='1')game.openInventory();else if(e.key==='Shift')game.toggleSneak()
 };window.addEventListener('keydown',key,true);return()=>window.removeEventListener('keydown',key,true)},[game,help,panel,confirmRestart,introOpen]);
 useEffect(()=>{const f=()=>setFullscreen(!!document.fullscreenElement);document.addEventListener('fullscreenchange',f);return()=>document.removeEventListener('fullscreenchange',f)},[]);
 useEffect(()=>{const director=new GameAudio(setAudioStatus);audio.current=director;return()=>{director.dispose();audio.current=null}},[]);
 useEffect(()=>{if(introOpen)return;audio.current?.sync(game);const timer=setInterval(()=>audio.current?.sync(game),80);return()=>clearInterval(timer)},[game,sound,language,introOpen]);
 const enableAudio=async(sync=true)=>{try{audioChoice.current=true;const enabled=await audio.current?.setEnabled(true);if(!enabled)return false;setSound(true);if(sync)audio.current?.sync(game);return true}catch{setAudioStatus(s=>({...s,error:'Audio is unavailable. Radio transcripts remain readable.'}));return false}};
 const toggleSound=async()=>{audioChoice.current=true;if(sound){await audio.current?.setEnabled(false);setSound(false)}else await enableAudio()};
 const startMission=(guided=game.tutorialEnabled)=>{if(!audioChoice.current)void enableAudio();game.start(guided)};
 const replayRadio=async(cue:RadioCue)=>{if(await enableAudio(false))void audio.current?.playRadio(cue,game.mode!=='playing',game.lastRadio.id)};
 const setAudioLevels=(music:number,voice:number)=>{setMusicLevel(music);setVoiceLevel(voice);audio.current?.setLevels(music,voice)};
 const openPanel=(next:'mission'|'radio'|'save'|'craft')=>{panelWasPlaying.current=game.mode==='playing';if(panelWasPlaying.current)game.pause();setPanel(next)};
 const closePanel=()=>{setPanel(null);if(panelWasPlaying.current&&game.mode==='paused'&&!document.hidden)game.start();panelWasPlaying.current=false};
 const toggleHelp=()=>{if(game.mode==='playing')game.pause();setHelp(true)};
 const requestRestart=()=>{if(game.mode==='playing')game.pause();setConfirmRestart(true)};
 const full=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await shell.current?.requestFullscreen()}catch{game.log('Fullscreen is not available in this window.')}};
 const evacuationFilm=game.level===2&&game.mode==='complete'&&!introOpen;
 const finishEvacuation=()=>{game.next();if(sound)void enableAudio(false)};
 useEffect(()=>{if(evacuationFilm)void audio.current?.setEnabled(false)},[evacuationFilm]);
 const closeIntro=()=>{audio.current?.stopRadio();setIntroOpen(false);try{markIntroSeen(localStorage)}catch{}};
 const resetView=()=>{setZoom(DEFAULT_ZOOM);setViewReset(n=>n+1)};
 const goals=game.objectives();const entity=game.selected||hover;const invIds=[...new Set<string>(game.inventory)];const selectedDef=inventoryItem?(ITEMS as any)[inventoryItem]:null;
 const guideTarget=tutorialTarget(game);const isStopped=!game.canAct;const command=(id:string)=>{setInventoryItem(id);game.use(id)};
 return <Localized><div className={`game-shell immersive-shell survival-hud sector-theme-${game.level}`} ref={shell}>
  {evacuationFilm&&<IntroCutscene kind="evac" audible={sound} onClose={finishEvacuation} portalContainer={fullscreen?shell.current:undefined}/>}
  {introOpen&&<IntroCutscene onClose={closeIntro} portalContainer={fullscreen?shell.current:undefined}/>}
  <header className="topbar">
   <a className="brand" href="#" onClick={e=>e.preventDefault()} aria-label="Ashfall Dead Sector"><span className="brand-symbol"><Biohazard size={28}/></span><span><strong>ASHFALL<span className="brand-dot">.</span></strong><small>DEAD SECTOR</small></span></a>
   <div className="world-clock"><span className="live-dot"/> DAY 1,247 <span className="divider">/</span> 06:42 <span className="weather">{game.data.weather}</span></div>
   <div className="top-actions"><RecordingControl getAudio={()=>audio.current?.recordingStream()||null} enableAudio={()=>enableAudio()} canStart={game.canAct}/><button className="hud-nav" onClick={()=>openPanel('craft')} title="Crafting"><Wrench size={18}/><span>Crafting</span></button><button className="save-button" onClick={()=>openPanel('save')} aria-label="Save and load" title="Save and load"><Save size={18}/><span>Save / Load</span></button><button className="language-toggle" onClick={()=>setLanguage(language==='de'?'en':'de')} aria-label={language==='de'?'Switch to English':'Auf Deutsch wechseln'}>{language==='de'?'DE':'EN'}</button><button className="hud-nav hud-mission-button" aria-label="Open mission objectives" title="Mission objectives" onClick={()=>openPanel('mission')}><Crosshair size={18}/><span>Mission</span></button><button className="hud-nav" aria-label="Open radio and audio controls" title="Radio & audio" onClick={()=>openPanel('radio')}><Radio size={18}/><span>Messages</span></button><button className="inventory-toggle" onClick={()=>game.openInventory()} aria-label="Open inventory" title="Open inventory (I)"><Backpack size={19}/><span>INVENTORY</span><kbd>I</kbd></button><button onClick={toggleSound} className={sound?'icon-btn active':'icon-btn'} title={sound?'Mute sound':'Enable sound'} aria-label={sound?'Mute sound':'Enable sound'}>{sound?<Volume2 size={18}/>:<VolumeX size={18}/>}</button><button className="icon-btn" onClick={toggleHelp} title="Controls and help" aria-label="Controls and help"><CircleHelp size={18}/></button><span className="action-divider"/><button className="pause-btn" onClick={()=>game.mode==='briefing'?startMission():game.pause()} disabled={['dead','complete','won'].includes(game.mode)}>{game.mode==='playing'?<Pause size={15}/>:<Play size={15}/>}<span>{game.mode==='playing'?'PAUSE':game.mode==='briefing'?'START':'RESUME'}</span><kbd>␣</kbd></button></div>
  </header>
  <div className="campaign-bar"><div className="campaign-label"><span>CAMPAIGN</span><strong>The Last Way Out</strong></div><ol className="chapters">{LEVELS.map((l:any,i:number)=><li key={l.name} className={game.level===i?'chapter current':game.unlocked>i?'chapter finished':'chapter locked'}><span className="chapter-number">{game.unlocked>i?<Check size={15}/>:String(i+1).padStart(2,'0')}</span><div><small>{i===LEVELS.length-1?'FINALE':`CHAPTER ${i+1}`}</small><span>{l.name}</span></div>{i>game.unlocked&&<LockKeyhole size={13} className="chapter-lock"/>}{i<2&&<ChevronRight className="chapter-arrow" size={18}/>}</li>)}</ol><div className="campaign-count">{String(game.level+1).padStart(2,'0')}<span> / {String(LEVELS.length).padStart(2,'0')}</span></div></div>
  <main className="play-layout">
   <section className={`playfield ${game.flash>.1?'damage-flash':''} ${game.tutorial.active?'guided-playfield':''}`} aria-label="Game world">
    <Scene game={game} onHover={setHover} zoom={zoom} onZoomChange={setZoom} viewReset={viewReset} rotation={rotation} following={following} onFollowChange={setFollowing}/>
    <div className="scene-vignette"/><div className="mobile-vitals"><Heart size={13}/>{Math.ceil(game.health)}<span>·</span><Shield size={13}/>{Math.round(game.protection*100)}%</div>
    <TutorialPanel game={game} portalContainer={fullscreen?shell.current:undefined}/>
    <div className="sector-heading"><div className="eyebrow"><span className="orange-dash"/>{game.data.tag}</div><h1>{game.data.place}</h1><p><MapPin size={12}/> {game.level===0?'52° 31′ N · 13° 24′ E':game.level===1?'28 M BELOW THE SURFACE':'LAST KNOWN LANDING ZONE'}</p></div>
    <div className="scene-status"><span className={game.mode==='playing'?'status-dot live':'status-dot'}/>{game.mode==='playing'&&game.tutorial.active&&game.tutorial.reading?'TRAINING · READING':game.mode==='playing'?'MISSION ACTIVE':game.mode==='paused'?'PAUSED':game.mode==='briefing'?'READY TO DEPLOY':game.mode==='dead'?'SIGNAL LOST':'SECTOR SECURED'}</div>
    {game.level===2&&game.signal>=0&&<div className={`evac-timer ${game.signal===0?'ready':''}`}><Radio size={20}/><span>{game.signal===0?'EVACUATION READY':'EVACUATION IN'}</span><strong>{game.signal===0?<CheckCheck size={24}/>:formatTime(Math.ceil(game.signal))}</strong></div>}
    <div className="map-south"><div className="scene-coordinates">S-{String(game.level+1).padStart(2,'0')} <span>·</span> X {game.player.x.toFixed(1)} <span>/</span> Y {game.player.y.toFixed(1)}</div><div className="zoom-tools" role="group" aria-label="Map zoom"><small>ZOOM</small><button className="icon-btn" onClick={()=>setZoom(z=>clampZoom(z/1.2))} disabled={zoom<=MIN_ZOOM+.001} aria-label="Zoom out" title="Zoom out (−)"><Minus size={19}/></button><output aria-label="Zoom level">{Math.round(zoom*100)}%</output><button className="icon-btn" onClick={()=>setZoom(z=>clampZoom(z*1.2))} disabled={zoom>=MAX_ZOOM-.001} aria-label="Zoom in" title="Zoom in (+)"><Plus size={19}/></button><button className="icon-btn zoom-reset" onClick={resetView} aria-label="Show whole map" title="Show whole map (0)"><Scan size={17}/><span>Overview</span></button><button className="icon-btn" onClick={full} aria-label={fullscreen?'Exit fullscreen':'Fullscreen'} title={fullscreen?'Exit fullscreen':'Fullscreen'}><Maximize2 size={17}/></button></div></div>
    <div className="minimap"><span>N <span>↑</span></span><svg viewBox="-1 -1 23 21" role="img" aria-label="Sector overview"><rect x="-.5" y="-.5" width="21" height="19" fill="#233b32"/>{game.entities.filter((e:any)=>!e.removed).map((e:any)=><rect key={e.id} x={e.x-.25} y={e.y-.25} width={e.w||.5} height={e.h||.5} fill={e.type==='prop'?'#647363':e.type==='exit'?'#edbb78':e.type==='item'?'#b1be8f':'#8b9d7b'}/>)}{game.zombies.filter((z:any)=>z.hp>0).map((z:any)=><circle key={z.id} cx={z.x} cy={z.y} r=".35" fill="#d78c68"/>)}<>{guideTarget&&<circle cx={guideTarget.x} cy={guideTarget.y} r=".85" fill="none" stroke="#ffd08c" strokeWidth=".28"/>}</><circle cx={game.player.x} cy={game.player.y} r=".55" fill="#ffe2a2"/><circle cx={game.player.x} cy={game.player.y} r="1.25" fill="none" stroke="#ffe2a2" strokeWidth=".12"/></svg><small>SECTOR OVERVIEW</small></div>
    {game.mode==='playing'&&<>
     <div className="field-feedback" aria-live="polite">{game.history.slice(0,2).map((event:any)=><p className={event.tone} key={event.id}><span/>{event.text}</p>)}</div>
     {game.throwing&&<div className="throw-prompt"><Wine size={18}/><span>Choose a throw target <small>Up to 9 tiles · ESC to cancel</small></span><button onClick={()=>{game.throwing=false;game.emit()}} aria-label="Cancel throw"><X size={17}/></button></div>}
     {entity&&!game.throwing&&<div className="entity-card"><span className={`entity-icon ${entity.type==='zombie'?'danger':''}`}>{entity.type==='item'?<ItemIcon id={entity.item}/>:entity.type==='zombie'?<ItemIcon id="zombie"/>:entity.type==='exit'||entity.type==='door'?<DoorOpen/>:entity.type==='generator'?<Zap/>:<Eye/>}</span><div><small>{entity.type==='item'?`${(ITEMS as any)[entity.item].weight.toFixed(1)} KG · PICK UP`:entity.type==='zombie'?`${Math.ceil(entity.hp)} / ${entity.maxHp} · ATTACK`:entity.type==='companion'?'COMPANION':entity.type==='prop'?'EXAMINE':entity.type==='container'&&entity.open&&!entity.contents.length?'EMPTY · SEARCHED':'INTERACT'}</small><strong>{entity.name}</strong><p>{entity.desc}</p></div>{entity.type!=='prop'&&<button aria-label={`Interact with ${entity.name}`} onClick={()=>entity.type==='companion'?game.openCompanion():game.select(entity.id)}><ArrowUpRight size={22}/></button>}</div>}
    </>}
    <div className="camera-orbit" role="group" aria-label="Camera controls"><strong>ROTATE CAMERA</strong><button onClick={()=>setRotation(v=>v-1)} title="Rotate left (Q)" aria-label="Rotate camera left">↶ <span>Left</span><kbd>Q</kbd></button><button aria-pressed={following} onClick={()=>setFollowing(v=>!v)} title="Keep Mara and Koda in view">{following?'Following':'Free camera'}</button><button onClick={()=>setRotation(v=>v+1)} title="Rotate right (E)" aria-label="Rotate camera right">↷ <span>Right</span><kbd>E</kbd></button></div>
    <div className="survival-dock"><div className="koda-commands" role="group" aria-label="Koda commands"><button onClick={()=>game.openCompanion()} disabled={isStopped}>Koda</button><button aria-pressed={game.companion.command==='assist'} disabled={isStopped} onClick={()=>game.commandCompanion('assist')} title="Stay close and defend Mara">Assist</button><button aria-pressed={game.companion.command==='search'} disabled={isStopped} onClick={()=>game.commandCompanion('search')} title="Find reachable supplies nearby">Search</button>{game.companion.foundId&&<button disabled={isStopped} onClick={()=>game.select(game.companion.foundId)}>Go to find</button>}</div>
    <div className="quickbar"><div className="quickslots">
     <button className="quickslot equipped" onClick={()=>game.openInventory()} title="Change held item in your backpack (1 / I)"><kbd>1</kbd><ItemIcon id={game.equipment.hand||'fists'} size={25}/><span>{game.equipment.hand?(ITEMS as any)[game.equipment.hand].name:'Fists'}</span><small>{game.meleeDamage} DAMAGE</small></button>
     <button className="quickslot" onClick={()=>command('medkit')} disabled={isStopped||!game.has('medkit')} title="Use Bandage"><kbd>2</kbd><ItemIcon id="medkit" size={25}/><b>{game.count('medkit')}</b><span>Bandage</span><small>+40 HP</small></button>
     <button className={`quickslot ${game.throwing?'throwing':''}`} onClick={()=>command('bottle')} disabled={isStopped||!game.has('bottle')} title="Throw bottle"><kbd>3</kbd><ItemIcon id="bottle" size={25}/><b>{game.count('bottle')}</b><span>Bottle</span><small>DISTRACT</small></button>
    </div><span className="quick-divider"/><button className={`stealth-btn ${game.sneak?'enabled':''}`} onClick={()=>game.toggleSneak()} disabled={isStopped}><Footprints size={20}/><span>{game.sneak?'Sneak':'Walk'}<small>SHIFT</small></span><span className="toggle-indicator"/></button></div></div>
   </section>
   <aside className="hud-sidebar" aria-label="Mission status">
    <div className="hud-survivor"><span className="eyebrow">SURVIVOR / 007</span><h2>Mara Voss</h2><div className="hud-vitals"><Heart size={15}/><strong>{Math.ceil(game.health)}<small> / 100</small></strong><span><Shield size={14}/>{Math.round(game.protection*100)}%</span></div><Progress locale="en-US" value={game.health} aria-label="Health" className="health-progress"/></div>
    <div className="hud-objectives"><div className="panel-label"><span>{'CHAPTER '+(game.level+1)} / {LEVELS.length}</span><button aria-label="Read mission details" onClick={()=>openPanel('mission')}><ArrowUpRight size={15}/></button></div><ul className="objectives">{game.data.goals.map((goal:string,i:number)=><li className={goals[i]?'done':'next'} key={goal}><span className="objective-check">{goals[i]?<Check size={12}/>:null}</span><span>{goal}</span></li>)}</ul>{game.entities.filter((e:any)=>e.remaining>0&&!e.done).map((e:any)=><p className="mission-work" key={e.id}>{language==='de'?'Sendepunkt halten':'Hold the transmission point'} · {Math.ceil(e.remaining)}s</p>)}</div>
    <button className="hud-pack" onClick={()=>game.openInventory()}><Backpack size={20}/><span><strong>Equipment</strong><small>{game.weight.toFixed(1)} / {CAPACITY} kg</small></span><kbd>I</kbd></button>
    <div className="hud-gear">{['hand','body','head'].map(slot=><button key={slot} onClick={()=>game.openInventory()} title={game.equipment[slot]?(ITEMS as any)[game.equipment[slot]].name:`Empty ${slot} slot`}>{game.equipment[slot]?<ItemIcon id={game.equipment[slot]} size={22}/>:<span aria-hidden="true" style={{width:44,height:44}}/>}<span>{slot.toUpperCase()}</span><i className={game.equipment[slot]?'filled':''}/></button>)}</div>
    <button className={`hud-radio ${audioStatus.playing?'transmitting':''}`} onClick={()=>openPanel('radio')}><Radio size={19}/><span><strong>{audioStatus.playing?'Incoming call':'Messages'}</strong><small>Radio, transcript & audio</small></span><ArrowUpRight size={15}/></button>
    <div className="companion-status"><strong>Koda · Shepherd puppy</strong><span>{game.companion.mode==='defend'?'Defending':game.companion.mode==='follow'?'Following':game.companion.mode==='search'?'Searching':game.companion.mode==='sniff'?'Sniffing':game.companion.mode==='found'?'Supplies found':'Resting'}</span></div><div className="hud-footer"><span>{formatTime(game.totalTime)} / {game.kills} eliminated</span><button aria-label="Restart sector" onClick={requestRestart}><RotateCcw size={15}/></button></div>
   </aside>
  </main>

  <Dialog open={game.companionOpen} onOpenChange={v=>{if(!v)game.closeCompanion()}}><DialogContent className="game-dialog koda-dialog" portalContainer={fullscreen?shell.current:undefined}><DialogTitle>Koda</DialogTitle><DialogDescription>Shepherd puppy · World paused</DialogDescription><ScrollRegion label="Koda"><KodaPreview game={game}/><p>Your loyal companion. Give him a task or take a quiet moment together.</p><div className="koda-care"><button onClick={()=>game.careCompanion('feed')} disabled={!game.has('ration')}>Feed · 1 canned food</button><button onClick={()=>game.careCompanion('play')}>Play with Koda</button></div><p aria-live="polite">{game.companion.care?.kind==='feed'?'Koda enjoys his food and wags his tail.':game.companion.care?.kind==='play'?'Koda bounds around happily.':'Ready for a little attention.'}</p><p>Bond <strong>{game.companion.bond} / 100</strong></p>{!game.has('ration')&&<p>Find canned food to feed Koda.</p>}<div className="koda-care"><button aria-pressed={game.companion.command==='assist'} onClick={()=>game.commandCompanion('assist')}>Assist</button><button aria-pressed={game.companion.command==='search'} onClick={()=>game.commandCompanion('search')}>Search</button></div><p>Assist: follow and defend. Search: sniff out nearby loot and mark it for Mara. Commands begin when you return to the game.</p><button className="primary-btn" onClick={()=>game.closeCompanion()}>BACK TO GAME <ArrowRight size={16}/></button></ScrollRegion></DialogContent></Dialog>
  <Dialog open={introOpen===false&&game.mode==='briefing'&&!game.inventoryOpen&&!panel&&!help&&!confirmRestart} onOpenChange={()=>{}}><DialogContent className="game-dialog phase-dialog" showCloseButton={false} portalContainer={fullscreen?shell.current:undefined}><DialogTitle className="sr-only">Sector briefing</DialogTitle><DialogDescription className="sr-only">Read your mission and choose how to begin.</DialogDescription><ScrollRegion label="Sector briefing"><div className="briefing-card"><div className="briefing-scene">{game.level<3?<img src={ART.sectors[game.level].src} alt={ART.sectors[game.level].alt}/>:<div className="colony-briefing-mark"><span>{game.data.tag}</span><strong>{game.data.safe||game.level===3||game.level===6?'SAFE ZONE':'FIELD MISSION'}</strong></div>}<span>SECTOR {String(game.level+1).padStart(2,'0')}</span></div><button className="secondary-btn briefing-save" onClick={()=>openPanel('save')}><Save size={17}/> Save / Load</button><div className="briefing-kicker"><LanguageSwitch/><Radio size={15}/> INCOMING TRANSMISSION</div><h2>{game.data.name}</h2><p>{game.data.intro}</p>{game.level<3&&<button className="briefing-radio" onClick={()=>replayRadio(game.lastRadio.voiceId)}><Volume2 size={14}/> Play radio briefing</button>}<button className="primary-btn" onClick={()=>startMission()}>{game.level===0?'START GUIDED TUTORIAL':'ENTER SECTOR'}<ArrowRight size={17}/></button>{game.level===0&&<button className="text-btn tutorial-direct" onClick={()=>startMission(false)}>Play without tutorial <ArrowUpRight size={14}/></button>}</div></ScrollRegion></DialogContent></Dialog>
  <Dialog open={!introOpen&&!evacuationFilm&&((game.mode==='paused'&&!game.companionOpen&&!game.inventoryOpen&&!game.lootOpen&&!panel&&!help&&!confirmRestart)||['complete','won','dead'].includes(game.mode)&&!game.inventoryOpen&&!panel&&!help&&!confirmRestart)} onOpenChange={v=>{if(!v&&game.mode==='paused')game.start()}}><DialogContent className="game-dialog phase-dialog" showCloseButton={false} portalContainer={fullscreen?shell.current:undefined}><DialogTitle className="sr-only">Mission status</DialogTitle><DialogDescription className="sr-only">Review your progress and continue the campaign.</DialogDescription><ScrollRegion label="Mission status">    {game.mode==='paused'&&!game.companionOpen&&!game.inventoryOpen&&!game.lootOpen&&!panel&&!help&&!confirmRestart&&<section className="state-card"><Pause size={26} className="state-icon"/><span className="eyebrow">A MOMENT OF QUIET</span><h2>Mission paused.</h2><p>Take a breath. Nothing moves while you rest.</p><button className="primary-btn" onClick={()=>startMission()}>RESUME GAME <Play size={15}/></button><button className="secondary-btn" onClick={()=>openPanel('save')}><Save size={17}/> Save / Load</button><button className="text-btn" onClick={requestRestart}><RotateCcw size={14}/> Restart sector</button></section>}
    {['complete','won','dead'].includes(game.mode)&&<section className={`state-card end-card ${game.mode==='dead'?'death':''}`}>
     {game.mode==='dead'?<img className="end-portrait" src="/images/openart/icons/zombie.webp" alt=""/>:game.mode==='won'?<Radio className="state-icon" size={38}/>:<DoorOpen className="state-icon" size={38}/>}
     <span className="eyebrow">{game.mode==='dead'?'SIGNAL CUT OFF':game.mode==='won'?'CAMPAIGN COMPLETE':'CHAPTER COMPLETE'}</span><h2>{game.mode==='dead'?'The city claimed you.':game.mode==='won'?'There is still a tomorrow.':'You are still here.'}</h2><p>{game.mode==='dead'?'Your equipment from the start of the sector is waiting for you. Use Bandages and keep moving.':game.mode==='won'?'Haven has clean water and power again. Imani is studying the sample. Tonight, Mara and Koda sleep behind safe walls.':game.level>=2?(game.level===2?'Mara and Koda are aboard. The helicopter carries you to Haven.':'Your work brings hope to Haven. Continue to the next mission.'):game.level===0?'The bunker gate opens. A sound comes from the darkness.':'The sample is secure. Your last chance awaits on the rooftop.'}</p>
     <>{game.level===0&&game.tutorial.completed&&<div className="tutorial-complete"><CheckCheck size={18}/> TRAINING COMPLETE · Ready for Station Zero</div>}</><div className="end-stats"><span><strong>{game.kills}</strong>INFECTED</span><span><strong>{formatTime(game.totalTime)}</strong>MISSION TIME</span><span><strong>{Math.ceil(game.health)}%</strong>HEALTH</span></div>
     <button className="primary-btn" onClick={()=>game.mode==='complete'?game.next():game.mode==='dead'?game.restart():game.newGame()}>{game.mode==='complete'?'ENTER NEXT SECTOR':game.mode==='dead'?'RETRY SECTOR':'NEW CAMPAIGN'}<ArrowRight size={17}/></button>
    </section>}
</ScrollRegion></DialogContent></Dialog>
  <Dialog open={!!panel} onOpenChange={v=>{if(!v)closePanel()}}><DialogContent className="game-dialog details-dialog" portalContainer={fullscreen?shell.current:undefined}><DialogTitle>{panel==='craft'?'Crafting':panel==='save'?'Save and load':panel==='radio'?'Messages':'Mission briefing'}</DialogTitle><DialogDescription>{panel==='craft'?'Turn scavenged supplies into useful equipment.':panel==='save'?'Keep your progress on this device.':panel==='radio'?'Mission chat, voice messages and journal.':'Your objectives and the path through this sector.'}</DialogDescription><ScrollRegion label={panel==='radio'?'Radio messages and audio settings':'Mission objectives'}>{panel==='craft'?<CraftingPanel game={game} onInventory={()=>{const resume=panelWasPlaying.current;panelWasPlaying.current=false;setPanel(null);if(resume&&game.mode==='paused')game.start();game.openInventory()}}/>:panel==='save'?<SavePanel game={game} onLoaded={()=>{panelWasPlaying.current=false;setPanel(null);setHover(null);setViewReset(v=>v+1)}}/>:panel==='radio'?<RadioPanel game={game} cue={game.lastRadio.voiceId} status={audioStatus} enabled={sound} music={musicLevel} voice={voiceLevel} onReplay={replayRadio} onStop={()=>audio.current?.stopRadio()} onToggle={toggleSound} onLevels={setAudioLevels}/>:<div className="mission-modal-content">{game.level<3?<img src={ART.sectors[game.level].src} alt={ART.sectors[game.level].alt}/>:<div className="colony-briefing-mark"><span>{game.data.tag}</span><strong>{game.data.safe||game.level===3||game.level===6?'SAFE ZONE':'FIELD MISSION'}</strong></div>}<h2>{game.data.name}</h2><p>{game.data.intro}</p><ul className="objectives">{game.data.goals.map((goal:string,i:number)=><li className={goals[i]?'done':'next'} key={goal}><span className="objective-check">{goals[i]?<Check size={12}/>:null}</span><span>{goal}</span></li>)}</ul><p>{game.data.hint}</p>{game.level<3&&<button className="secondary-btn" onClick={()=>replayRadio((['checkpoint','bunker','rooftop'] as RadioCue[])[game.level%3])}><Radio size={14}/> Play mission call</button>}</div>}</ScrollRegion><button className="primary-btn" onClick={closePanel}>BACK TO GAME <ArrowRight size={15}/></button></DialogContent></Dialog>
  <InventoryDialog game={game} onCraft={()=>{game.closeInventory();openPanel('craft')}} portalContainer={fullscreen?shell.current:undefined}/>
  <Dialog open={help} onOpenChange={setHelp}><DialogContent className="game-dialog details-dialog" portalContainer={fullscreen?shell.current:undefined}><DialogTitle>Surviving Ashfall</DialogTitle><DialogDescription>Escape the city, reach Haven and help the colony survive. Use the radio panel for voiced mission calls, transcripts, and music or voice levels.</DialogDescription><ScrollRegion label="Controls and help"><button className="secondary-btn" onClick={()=>{setHelp(false);setIntroOpen(true)}}>{language==='de'?'Intro erneut ansehen':'Watch intro again'}</button><div className="help-list"><p><Crosshair/><span><strong>Follow and rotate</strong>The camera follows Mara and Koda when zoomed in. Use Q / E or the arrow buttons to rotate. Dragging switches to Free camera; select Following to return.</span></p><p><MousePointer2/><span><strong>Click to move</strong>Click an open tile and Mara will find a path. Click an item to walk over and interact automatically. Hold the right mouse button and drag to pan the view.</span></p><p><Plus/><span><strong>Get closer or see it all</strong>Use the mouse wheel or pinch with two fingers to zoom from 65% to 320%. On mobile, drag to pan the map. The bottom-right controls include plus, minus, and Overview. When the map is focused, you can also use +, −, and 0.</span></p><p><Backpack/><span><strong>Carry what you can</strong>Press I or select the backpack button to open your inventory and pause the mission. Open cars, storage boxes and drawers to view their contents. Take individual items or drag them to your backpack. Equip an item in your hand, on your body, or on your head. Only worn armor protects you; only your held weapon determines melee damage. Use or drop items from your backpack. You can carry up to 14 kg.</span></p><p><Skull/><span><strong>Choose your battles</strong>Click an Infected to attack. Mara automatically defends herself at close range. Press SHIFT to move more quietly and slowly.</span></p><p><Wine/><span><strong>Distract and survive</strong>Press 2 to use a Bandage. Press 3 to ready a bottle, then click an open tile within 9 tiles. Infected follow the noise for 8 seconds.</span></p><p><DoorOpen/><span><strong>Find a way out</strong>Doors and devices tell you what they need. Quest items are used automatically when you interact. Press Space to pause.</span></p></div></ScrollRegion><button className="primary-btn" onClick={()=>{setHelp(false);if(game.mode==='paused')game.start()}}>GOT IT <Check size={16}/></button></DialogContent></Dialog>
  <Dialog open={confirmRestart} onOpenChange={setConfirmRestart}><DialogContent className="game-dialog restart-dialog" portalContainer={fullscreen?shell.current:undefined}><DialogTitle>Restart sector?</DialogTitle><DialogDescription>Restart this sector with the health and equipment you had when you entered. Previously completed chapters stay complete.</DialogDescription><div className="restart-actions"><button className="secondary-btn" onClick={()=>setConfirmRestart(false)}>Cancel</button><button className="primary-btn" onClick={()=>{setConfirmRestart(false);setInventoryItem(null);game.restart()}}>RESTART <RotateCcw size={15}/></button></div></DialogContent></Dialog>
 </div></Localized>
}

export default function LocalizedGame(){return <LanguageProvider><GameClient/></LanguageProvider>}
