'use client';
import { useEffect, useRef, useState } from 'react';
import dynamic from 'next/dynamic';
import { Biohazard, ArrowUpRight, ArrowRight, Backpack, Battery, Check, CheckCheck, ChevronRight, CircleHelp, Crosshair, Scan, Droplet, Footprints, Heart, KeyRound, LockKeyhole, MapPin, Maximize2, Minus, Package, Pause, Play, Plus, Radio, RotateCcw, Shield, Skull, Volume2, VolumeX, Wrench, Zap, X, FlaskConical, DoorOpen, MousePointer2, Circle, Eye, Wine, Utensils, Armchair } from 'lucide-react';
import { Dialog, DialogContent, DialogDescription, DialogTitle } from '@/components/ui/dialog';
import { Progress } from '@/components/ui/progress';
import { Game, ITEMS, CAPACITY, LEVELS } from './engine.mjs';
import { ART } from './art';
import InventoryDialog from './InventoryDialog';
import ItemIcon from './ItemIcon';
import TutorialPanel from './TutorialPanel';
import RadioPanel from './RadioPanel';
import { GameAudio, type AudioStatus, type RadioCue } from './GameAudio';
import { tutorialTarget } from './tutorial.mjs';
import { DEFAULT_ZOOM, MIN_ZOOM, MAX_ZOOM, clampZoom } from './camera-settings.mjs';
const Scene=dynamic(()=>import('./Scene'),{ssr:false,loading:()=> <div className="loading-scene"><Biohazard/><span>SCOUTING SECTOR</span></div>});
const formatTime=(time:number)=>`${Math.floor(time/60).toString().padStart(2,'0')}:${Math.floor(time%60).toString().padStart(2,'0')}`;
export default function GameClient(){
 const [game]=useState<any>(()=>new Game({tutorial:true}));const [,refresh]=useState(0);const [hover,setHover]=useState<any>(null);const [inventoryItem,setInventoryItem]=useState<string|null>(null);const [help,setHelp]=useState(false);const [confirmRestart,setConfirmRestart]=useState(false);const [zoom,setZoom]=useState(DEFAULT_ZOOM);const [viewReset,setViewReset]=useState(0);const [sound,setSound]=useState(false);const [fullscreen,setFullscreen]=useState(false);const shell=useRef<HTMLDivElement>(null);const audio=useRef<GameAudio|null>(null);const audioChoice=useRef(false);const [audioStatus,setAudioStatus]=useState<AudioStatus>({cue:null,playing:false,loading:false,error:null});const [musicLevel,setMusicLevel]=useState(.38);const [voiceLevel,setVoiceLevel]=useState(.85);
 useEffect(()=>game.subscribe(()=>refresh(n=>n+1)),[game]);
 useEffect(()=>{const onVisibility=()=>{if(document.hidden){if(game.inventoryOpen&&game.inventoryReturnMode==='playing'){game.inventoryReturnMode='paused';game.emit()}else if(game.mode==='playing')game.pause()}};document.addEventListener('visibilitychange',onVisibility);return()=>document.removeEventListener('visibilitychange',onVisibility)},[game]);
 useEffect(()=>{const key=(e:KeyboardEvent)=>{
  if(e.ctrlKey||e.metaKey||e.altKey)return;
  const target=e.target as HTMLElement;
  if(game.inventoryOpen){if(e.key.toLowerCase()==='i'||e.key==='Escape'){e.preventDefault();e.stopPropagation();if(!e.repeat)game.closeInventory()}return;}
  if(help||confirmRestart||target?.isContentEditable||['INPUT','TEXTAREA','SELECT'].includes(target?.tagName))return;
  if(e.key.toLowerCase()==='i'){e.preventDefault();e.stopPropagation();if(!e.repeat)game.openInventory();return;}
  if(e.key===' '&&target?.closest('button'))return;
  if([' ','Escape','1','2','3','Shift'].includes(e.key))e.preventDefault();
  if(e.repeat)return;
  if(e.key===' '||e.key==='Escape'){if(game.throwing){game.throwing=false;game.emit()}else game.pause()}
  else if(e.key==='2')game.use('medkit');else if(e.key==='3')game.use('bottle');else if(e.key==='1')game.openInventory();else if(e.key==='Shift')game.toggleSneak()
 };window.addEventListener('keydown',key,true);return()=>window.removeEventListener('keydown',key,true)},[game,help,confirmRestart]);
 useEffect(()=>{const f=()=>setFullscreen(!!document.fullscreenElement);document.addEventListener('fullscreenchange',f);return()=>document.removeEventListener('fullscreenchange',f)},[]);
 useEffect(()=>{const director=new GameAudio(setAudioStatus);audio.current=director;return()=>{director.dispose();audio.current=null}},[]);
 useEffect(()=>{audio.current?.sync(game)},[game,game.lastRadio?.id,game.mode,game.inventoryOpen,game.tutorial.reading,sound]);
 const enableAudio=async(sync=true)=>{try{audioChoice.current=true;const enabled=await audio.current?.setEnabled(true);if(!enabled)return false;setSound(true);if(sync)audio.current?.sync(game);return true}catch{setAudioStatus(s=>({...s,error:'Audio is unavailable. Radio transcripts remain readable.'}));return false}};
 const toggleSound=async()=>{audioChoice.current=true;if(sound){await audio.current?.setEnabled(false);setSound(false)}else await enableAudio()};
 const startMission=(guided=game.tutorialEnabled)=>{if(!audioChoice.current)void enableAudio();game.start(guided)};
 const replayRadio=async(cue:RadioCue)=>{if(await enableAudio(false))void audio.current?.playRadio(cue,game.mode!=='playing',game.lastRadio.id)};
 const setAudioLevels=(music:number,voice:number)=>{setMusicLevel(music);setVoiceLevel(voice);audio.current?.setLevels(music,voice)};
 const toggleHelp=()=>{if(game.mode==='playing')game.pause();setHelp(true)};
 const requestRestart=()=>{if(game.mode==='playing')game.pause();setConfirmRestart(true)};
 const full=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await shell.current?.requestFullscreen()}catch{game.log('Fullscreen is not available in this window.')}};
 const resetView=()=>{setZoom(DEFAULT_ZOOM);setViewReset(n=>n+1)};
 const goals=game.objectives();const entity=game.selected||hover;const invIds=[...new Set<string>(game.inventory)];const selectedDef=inventoryItem?(ITEMS as any)[inventoryItem]:null;
 const guideTarget=tutorialTarget(game);const isStopped=!game.canAct;const command=(id:string)=>{setInventoryItem(id);game.use(id)};
 return <div className={`game-shell sector-theme-${game.level}`} ref={shell}>
  <header className="topbar">
   <a className="brand" href="#" onClick={e=>e.preventDefault()} aria-label="Ashfall Dead Sector"><span className="brand-symbol"><Biohazard size={28}/></span><span><strong>ASHFALL<span className="brand-dot">.</span></strong><small>DEAD SECTOR</small></span></a>
   <div className="world-clock"><span className="live-dot"/> DAY 1,247 <span className="divider">/</span> 06:42 <span className="weather">{game.data.weather}</span></div>
   <div className="top-actions"><button className="inventory-toggle" onClick={()=>game.openInventory()} aria-label="Open inventory" title="Open inventory (I)"><Backpack size={19}/><span>INVENTORY</span><kbd>I</kbd></button><button onClick={toggleSound} className={sound?'icon-btn active':'icon-btn'} title={sound?'Mute sound':'Enable sound'} aria-label={sound?'Mute sound':'Enable sound'}>{sound?<Volume2 size={18}/>:<VolumeX size={18}/>}</button><button className="icon-btn" onClick={toggleHelp} title="Controls and help" aria-label="Controls and help"><CircleHelp size={18}/></button><span className="action-divider"/><button className="pause-btn" onClick={()=>game.mode==='briefing'?startMission():game.pause()} disabled={['dead','complete','won'].includes(game.mode)}>{game.mode==='playing'?<Pause size={15}/>:<Play size={15}/>}<span>{game.mode==='playing'?'PAUSE':game.mode==='briefing'?'START':'RESUME'}</span><kbd>␣</kbd></button></div>
  </header>
  <div className="campaign-bar"><div className="campaign-label"><span>CAMPAIGN</span><strong>The Last Way Out</strong></div><ol className="chapters">{LEVELS.map((l:any,i:number)=><li key={l.name} className={game.level===i?'chapter current':game.unlocked>i?'chapter finished':'chapter locked'}><span className="chapter-number">{game.unlocked>i?<Check size={15}/>:String(i+1).padStart(2,'0')}</span><div><small>{i===2?'FINALE':`CHAPTER ${i+1}`}</small><span>{l.name}</span></div>{i>game.unlocked&&<LockKeyhole size={13} className="chapter-lock"/>}{i<2&&<ChevronRight className="chapter-arrow" size={18}/>}</li>)}</ol><div className="campaign-count">0{game.level+1}<span> / 03</span></div></div>
  <main className="play-layout">
   <section className={`playfield ${game.flash>.1?'damage-flash':''} ${game.tutorial.active?'guided-playfield':''}`} aria-label="Game world">
    <Scene game={game} onHover={setHover} zoom={zoom} onZoomChange={setZoom} viewReset={viewReset}/>
    <div className="scene-vignette"/>
    <TutorialPanel game={game}/>
    <div className="sector-heading"><div className="eyebrow"><span className="orange-dash"/>{game.data.tag}</div><h1>{game.data.place}</h1><p><MapPin size={12}/> {game.level===0?'52° 31′ N · 13° 24′ E':game.level===1?'28 M BELOW THE SURFACE':'LAST KNOWN LANDING ZONE'}</p></div>
    <div className="scene-status"><span className={game.mode==='playing'?'status-dot live':'status-dot'}/>{game.mode==='playing'&&game.tutorial.active&&game.tutorial.reading?'TRAINING · READING':game.mode==='playing'?'MISSION ACTIVE':game.mode==='paused'?'PAUSED':game.mode==='briefing'?'READY TO DEPLOY':game.mode==='dead'?'SIGNAL LOST':'SECTOR SECURED'}</div>
    {game.level===2&&game.signal>=0&&<div className={`evac-timer ${game.signal===0?'ready':''}`}><Radio size={20}/><span>{game.signal===0?'EVACUATION READY':'EVACUATION IN'}</span><strong>{game.signal===0?<CheckCheck size={24}/>:formatTime(Math.ceil(game.signal))}</strong></div>}
    <div className="map-south"><div className="scene-coordinates">S-{String(game.level+1).padStart(2,'0')} <span>·</span> X {game.player.x.toFixed(1)} <span>/</span> Y {game.player.y.toFixed(1)}</div><div className="zoom-tools" role="group" aria-label="Map zoom"><small>ZOOM</small><button className="icon-btn" onClick={()=>setZoom(z=>clampZoom(z/1.2))} disabled={zoom<=MIN_ZOOM+.001} aria-label="Zoom out" title="Zoom out (−)"><Minus size={19}/></button><output aria-label="Zoom level">{Math.round(zoom*100)}%</output><button className="icon-btn" onClick={()=>setZoom(z=>clampZoom(z*1.2))} disabled={zoom>=MAX_ZOOM-.001} aria-label="Zoom in" title="Zoom in (+)"><Plus size={19}/></button><button className="icon-btn zoom-reset" onClick={resetView} aria-label="Show whole map" title="Show whole map (0)"><Scan size={17}/><span>Overview</span></button><button className="icon-btn" onClick={full} aria-label={fullscreen?'Exit fullscreen':'Fullscreen'} title={fullscreen?'Exit fullscreen':'Fullscreen'}><Maximize2 size={17}/></button></div></div>
    <div className="minimap"><span>N <span>↑</span></span><svg viewBox="-1 -1 23 21" role="img" aria-label="Sector overview"><rect x="-.5" y="-.5" width="21" height="19" fill="#233b32"/>{game.entities.filter((e:any)=>!e.removed).map((e:any)=><rect key={e.id} x={e.x-.25} y={e.y-.25} width={e.w||.5} height={e.h||.5} fill={e.type==='prop'?'#647363':e.type==='exit'?'#edbb78':e.type==='item'?'#b1be8f':'#8b9d7b'}/>)}{game.zombies.filter((z:any)=>z.hp>0).map((z:any)=><circle key={z.id} cx={z.x} cy={z.y} r=".35" fill="#d78c68"/>)}<>{guideTarget&&<circle cx={guideTarget.x} cy={guideTarget.y} r=".85" fill="none" stroke="#ffd08c" strokeWidth=".28"/>}</><circle cx={game.player.x} cy={game.player.y} r=".55" fill="#ffe2a2"/><circle cx={game.player.x} cy={game.player.y} r="1.25" fill="none" stroke="#ffe2a2" strokeWidth=".12"/></svg><small>SECTOR OVERVIEW</small></div>
    {game.mode==='playing'&&<>
     <div className="field-feedback" aria-live="polite">{game.history.slice(0,2).map((event:any)=><p className={event.tone} key={event.id}><span/>{event.text}</p>)}</div>
     {game.throwing&&<div className="throw-prompt"><Wine size={18}/><span>Choose a throw target <small>Up to 9 tiles · ESC to cancel</small></span><button onClick={()=>{game.throwing=false;game.emit()}} aria-label="Cancel throw"><X size={17}/></button></div>}
     {entity&&!game.throwing&&<div className="entity-card"><span className={`entity-icon ${entity.type==='zombie'?'danger':''}`}>{entity.type==='item'?<ItemIcon id={entity.item}/>:entity.type==='zombie'?<ItemIcon id="zombie"/>:entity.type==='exit'||entity.type==='door'?<DoorOpen/>:entity.type==='generator'?<Zap/>:<Eye/>}</span><div><small>{entity.type==='item'?`${(ITEMS as any)[entity.item].weight.toFixed(1)} KG · PICK UP`:entity.type==='zombie'?`${Math.ceil(entity.hp)} / ${entity.maxHp} · ATTACK`:entity.type==='prop'?'EXAMINE':entity.type==='container'&&entity.open&&!entity.contents.length?'EMPTY · SEARCHED':'INTERACT'}</small><strong>{entity.name}</strong><p>{entity.desc}</p></div>{entity.type!=='prop'&&<button aria-label={`Interact with ${entity.name}`} onClick={()=>game.select(entity.id)}><ArrowUpRight size={22}/></button>}</div>}
    </>}
    {game.mode==='briefing'&&<div className="briefing-card"><div className="briefing-scene"><img src={ART.sectors[game.level].src} alt={ART.sectors[game.level].alt}/><span>SECTOR 0{game.level+1}</span></div><div className="briefing-kicker"><Radio size={15}/> INCOMING TRANSMISSION <span>0{game.level+1}</span></div><h2>{game.data.name}</h2><p>{game.data.intro}</p><button className="briefing-radio" onClick={()=>replayRadio(game.lastRadio.voiceId)}><Volume2 size={14}/> Play radio briefing</button><div className="briefing-tip"><MousePointer2 size={17}/><span>Click the ground to move.<br/>Click objects to examine them.</span></div><button className="primary-btn" onClick={()=>startMission()}>{game.level===0?'START GUIDED TUTORIAL':'ENTER SECTOR'} <ArrowRight size={17}/></button>{game.level===0&&<><p className="tutorial-start-note">Learn the controls through this mission, one task at a time.</p><button className="text-btn tutorial-direct" onClick={()=>startMission(false)}>Play without tutorial <ArrowUpRight size={14}/></button></>}</div>}
    {game.mode==='paused'&&!game.inventoryOpen&&<div className="state-overlay"><div className="state-card"><Pause size={26} className="state-icon"/><span className="eyebrow">A MOMENT OF QUIET</span><h2>Mission paused.</h2><p>Take a breath. Nothing moves while you rest.</p><button className="primary-btn" onClick={()=>startMission()}>RESUME GAME <Play size={15}/></button><button className="text-btn" onClick={requestRestart}><RotateCcw size={14}/> Restart sector</button></div></div>}
    {['complete','won','dead'].includes(game.mode)&&<div className="state-overlay"><div className={`state-card end-card ${game.mode==='dead'?'death':''}`}>
     {game.mode==='dead'?<img className="end-portrait" src="/images/openart/icons/zombie.webp" alt=""/>:game.mode==='won'?<Radio className="state-icon" size={38}/>:<DoorOpen className="state-icon" size={38}/>}
     <span className="eyebrow">{game.mode==='dead'?'SIGNAL CUT OFF':game.mode==='won'?'CAMPAIGN COMPLETE':'CHAPTER COMPLETE'}</span><h2>{game.mode==='dead'?'The city claimed you.':game.mode==='won'?'There is still a tomorrow.':'You are still here.'}</h2><p>{game.mode==='dead'?'Your equipment from the start of the sector is waiting for you. Use Bandages and keep moving.':game.mode==='won'?'The rotors drown out the city. You and Sample N-04 are safe. Three sectors. A second chance.':game.level===0?'The bunker gate opens. A sound comes from the darkness.':'The sample is secure. Your last chance awaits on the rooftop.'}</p>
     <>{game.level===0&&game.tutorial.completed&&<div className="tutorial-complete"><CheckCheck size={18}/> TRAINING COMPLETE · Ready for Station Zero</div>}</><div className="end-stats"><span><strong>{game.kills}</strong>INFECTED</span><span><strong>{formatTime(game.totalTime)}</strong>MISSION TIME</span><span><strong>{Math.ceil(game.health)}%</strong>HEALTH</span></div>
     <button className="primary-btn" onClick={()=>game.mode==='complete'?game.next():game.mode==='dead'?game.restart():game.newGame()}>{game.mode==='complete'?'ENTER NEXT SECTOR':game.mode==='dead'?'RETRY SECTOR':'NEW CAMPAIGN'}<ArrowRight size={17}/></button>
    </div></div>}
    <div className="quickbar"><div className="quickslots">
     <button className="quickslot equipped" onClick={()=>game.openInventory()} title="Change held item in your backpack (1 / I)"><kbd>1</kbd><ItemIcon id={game.equipment.hand||'fists'} size={25}/><span>{game.equipment.hand?(ITEMS as any)[game.equipment.hand].name:'Fists'}</span><small>{game.meleeDamage} DAMAGE</small></button>
     <button className="quickslot" onClick={()=>command('medkit')} disabled={isStopped||!game.has('medkit')} title="Use Bandage"><kbd>2</kbd><ItemIcon id="medkit" size={25}/><b>{game.count('medkit')}</b><span>Bandage</span><small>+40 HP</small></button>
     <button className={`quickslot ${game.throwing?'throwing':''}`} onClick={()=>command('bottle')} disabled={isStopped||!game.has('bottle')} title="Throw bottle"><kbd>3</kbd><ItemIcon id="bottle" size={25}/><b>{game.count('bottle')}</b><span>Bottle</span><small>DISTRACT</small></button>
    </div><span className="quick-divider"/><button className={`stealth-btn ${game.sneak?'enabled':''}`} onClick={()=>game.toggleSneak()} disabled={isStopped}><Footprints size={20}/><span>{game.sneak?'Sneak':'Walk'}<small>SHIFT</small></span><span className="toggle-indicator"/></button></div>
   </section>
   <aside className="sidebar">
    <section className="survivor-section"><div className="panel-label"><span>SURVIVOR</span><span className="id-label">ID — 007</span></div><div className="survivor"><span className="survivor-avatar"><img src="/images/openart/icons/mara.webp" alt="Mara Voss"/><i/></span><div><h2>Mara Voss</h2><p>{game.health>65?'Stable. Still alive.':game.health>30?'Injured. Time for a Bandage.':'Critical. Find cover.'}</p></div><span className="survivor-level">07</span></div><div className="vital-label"><span><Heart size={13}/> Health</span><strong>{Math.ceil(game.health)} <small>/ 100</small></strong></div><Progress locale="en-US" className={`health-progress ${game.health<35?'critical':''}`} value={game.health} aria-label="Health"/><div className="vital-meta"><span><span className={game.sneak?'noise-dot quiet':'noise-dot'}/>{game.sneak?'QUIET':game.noise>.5?'AUDIBLE':'LOW PROFILE'}</span><span title="Damage reduction from worn equipment"><Shield size={12}/> {Math.round(game.protection*100)}% PROTECTION</span></div></section>
    <section className="mission-section"><div className="panel-label"><span>CURRENT OBJECTIVE</span><Crosshair size={14}/></div><div className="mission-art"><img src={ART.sectors[game.level].src} alt={ART.sectors[game.level].alt}/><div/><span>0{game.level+1} <small>/ 03</small></span><strong>{game.level===0?'A way down.':game.level===1?'Hope beneath the concrete.':'One last call.'}</strong></div><ul className="objectives">{game.data.goals.map((goal:string,i:number)=><li key={goal} className={goals[i]?'done':i===goals.findIndex((v:boolean)=>!v)?'next':''}><span className="objective-check">{goals[i]?<Check size={12}/>:i===goals.findIndex((v:boolean)=>!v)?<span/>:null}</span><span>{goal}</span></li>)}</ul><button className="hint-btn" onClick={()=>{game.log(game.data.hint,'story');void replayRadio((['checkpoint','bunker','rooftop'] as RadioCue[])[game.level])}}><Radio size={13}/> Replay mission call <ArrowUpRight size={13}/></button></section>
    <RadioPanel cue={game.lastRadio.voiceId} status={audioStatus} enabled={sound} music={musicLevel} voice={voiceLevel} onReplay={replayRadio} onStop={()=>audio.current?.stopRadio()} onToggle={toggleSound} onLevels={setAudioLevels}/>
    <section className="inventory-section"><button className="inventory-expand" onClick={()=>game.openInventory()}><Backpack size={17}/> Open inventory <kbd>I</kbd><ArrowUpRight size={17}/></button><div className="panel-label"><span><Backpack size={15}/> BACKPACK</span><span className={game.weight>12?'weight heavy':'weight'}>{game.weight.toFixed(1)} <small>/ {CAPACITY} KG</small></span></div><Progress locale="en-US" className="weight-progress" value={game.weight/CAPACITY*100} aria-label="Carry weight"/>
     <div className="inventory-grid">{invIds.map(id=><button key={id} onClick={()=>setInventoryItem(inventoryItem===id?null:id)} className={`inventory-tile ${(ITEMS as any)[id].kind==='quest'?'quest-item':''} ${inventoryItem===id?'selected':''}`} aria-label={`${(ITEMS as any)[id].name}, quantity: ${game.count(id)}`} title={(ITEMS as any)[id].name}><ItemIcon id={id} size={24}/><span>{(ITEMS as any)[id].name}</span><b>{game.count(id)>1?`×${game.count(id)}`:''}</b>{(ITEMS as any)[id].kind==='quest'&&<i/>}</button>)}{Array.from({length:Math.max(0,6-invIds.length)}).map((_,i)=><div className="inventory-empty" key={i}><Plus size={13}/></div>)}</div>
     {selectedDef&&game.has(inventoryItem)&&<div className="inventory-detail"><div><strong>{selectedDef.name}</strong><span>{selectedDef.weight.toFixed(1)} kg</span></div><p>{selectedDef.desc}</p><div className="inventory-item-actions">{['heal','food','throw'].includes(selectedDef.kind)&&<button disabled={isStopped} onClick={()=>game.use(inventoryItem)}>{selectedDef.kind==='throw'?'Throw':'Use'}<ArrowUpRight size={13}/></button>}{selectedDef.slot&&<button disabled={isStopped} onClick={()=>game.equip(inventoryItem)}>{game.equipment[selectedDef.slot]===inventoryItem?'Unequip':'Equip'}<Shield size={13}/></button>}<button disabled={isStopped} onClick={()=>game.drop(inventoryItem)}>Drop <ArrowRight size={13}/></button></div></div>}
     {!selectedDef&&<p className="inventory-hint">Select an item to use or drop it.</p>}
    </section>
    <div className="sidebar-footer"><span><span className="live-dot"/> {game.mode==='dead'?'CONNECTION LOST':'FREQUENCY 104.8'}</span><button onClick={requestRestart} aria-label="Restart sector" title="Restart sector"><RotateCcw size={14}/></button></div>
   </aside>
  </main>
  <footer className="instruction-strip"><span><MousePointer2 size={13}/><strong>CLICK</strong> Move & interact</span><span><Skull size={13}/><strong>CLICK INFECTED</strong> Attack</span><span><Footprints size={13}/><strong>SHIFT</strong> Sneak</span><span className="zoom-help"><Plus size={13}/><strong>WHEEL / TWO FINGERS</strong> Zoom</span><span className="pan-help"><MousePointer2 size={13}/><strong>RIGHT-DRAG</strong> Pan view</span></footer>
  <InventoryDialog game={game} portalContainer={fullscreen?shell.current:undefined}/>
  <Dialog open={help} onOpenChange={setHelp}><DialogContent className="game-dialog"><DialogTitle>Surviving Ashfall</DialogTitle><DialogDescription>Three sectors. One final evacuation. Use the radio panel for voiced mission calls, transcripts, and music or voice levels.</DialogDescription><div className="help-list"><p><MousePointer2/><span><strong>Click to move</strong>Click an open tile and Mara will find a path. Click an item to walk over and interact automatically. Hold the right mouse button and drag to pan the view.</span></p><p><Plus/><span><strong>Get closer or see it all</strong>Use the mouse wheel or pinch with two fingers to zoom from 65% to 320%. On mobile, drag to pan the map. The bottom-right controls include plus, minus, and Overview. When the map is focused, you can also use +, −, and 0.</span></p><p><Backpack/><span><strong>Carry what you can</strong>Press I or select the backpack button to open your inventory and pause the mission. Search containers and collect loose items. Equip an item in your hand, on your body, or on your head. Only worn armor protects you; only your held weapon determines melee damage. Use or drop items from your backpack. You can carry up to 14 kg.</span></p><p><Skull/><span><strong>Choose your battles</strong>Click an Infected to attack. Mara automatically defends herself at close range. Press SHIFT to move more quietly and slowly.</span></p><p><Wine/><span><strong>Distract and survive</strong>Press 2 to use a Bandage. Press 3 to ready a bottle, then click an open tile within 9 tiles. Infected follow the noise for 8 seconds.</span></p><p><DoorOpen/><span><strong>Find a way out</strong>Doors and devices tell you what they need. Quest items are used automatically when you interact. Press Space to pause.</span></p></div><button className="primary-btn" onClick={()=>{setHelp(false);if(game.mode==='paused')game.start()}}>GOT IT <Check size={16}/></button></DialogContent></Dialog>
  <Dialog open={confirmRestart} onOpenChange={setConfirmRestart}><DialogContent className="game-dialog restart-dialog"><DialogTitle>Restart sector?</DialogTitle><DialogDescription>Restart this sector with the health and equipment you had when you entered. Previously completed chapters stay complete.</DialogDescription><div className="restart-actions"><button className="secondary-btn" onClick={()=>setConfirmRestart(false)}>Cancel</button><button className="primary-btn" onClick={()=>{setConfirmRestart(false);setInventoryItem(null);game.restart()}}>RESTART <RotateCcw size={15}/></button></div></DialogContent></Dialog>
 </div>
}
