'use client';
import {Localized,useLanguage} from './i18n';
import {Play,Square,Volume2,VolumeX,MessageCircle,Film,ListChecks,Radio} from 'lucide-react';
import {RADIO} from './radio.mjs';
import {ART} from './art';
import type {AudioStatus,RadioCue} from './GameAudio';
export type RadioTab='messages'|'missions'|'videos'|'audio';
export default function RadioPanel({game,cue,status,enabled,music,voice,onReplay,onStop,onToggle,onLevels,films,onFilm,tab,onTabChange}:{game:any;cue:RadioCue;status:AudioStatus;enabled:boolean;music:number;voice:number;onReplay:(cue:RadioCue)=>void;onStop:()=>void;onToggle:()=>void;onLevels:(music:number,voice:number)=>void;films:{id:string;title:string;deTitle:string;chapter:number}[];onFilm:(id:'intro'|'evac')=>void;tab:RadioTab;onTabChange:(tab:RadioTab)=>void}){
 const {language}=useLanguage(),de=language==='de',t=(en:string,ger:string)=>de?ger:en;
 const current=status.playing&&status.cue?status.cue:cue,call=RADIO[current];
 const tabs=[{id:'messages',label:t('Messages','Nachrichten'),icon:MessageCircle},{id:'missions',label:t('Objectives','Aufträge'),icon:ListChecks},{id:'videos',label:t('Videos','Videos'),icon:Film},{id:'audio',label:t('Sound','Ton'),icon:Volume2}] as const;
 return <Localized><section className="comms-panel" aria-label={t('ASH Link communications','ASH Link Kommunikation')}>
  <div className="comms-heading"><span className="comms-emblem"><Radio size={23}/></span><div><strong>ASH / LINK</strong><small>{t('Control · Mara · Koda','Leitstelle · Mara · Koda')}</small></div><span className="comms-signal">104.8 FM</span></div>
  <div className="comms-tabs" role="group" aria-label={t('Communication sections','Kommunikationsbereiche')}>{tabs.map(({id,label,icon:Icon})=><button key={id} aria-pressed={tab===id} onClick={()=>onTabChange(id)}><Icon size={16}/>{label}{id==='videos'&&<small>{films.length}</small>}</button>)}</div>
  {tab==='messages'&&<div className="comms-messages"><div className="comms-section-label">{t('LATEST MESSAGES','NEUESTE NACHRICHTEN')}<span>{game.messages.length}</span></div>{[...game.messages].reverse().map((m:any)=>{const active=status.cue===m.voiceId&&(status.playing||status.loading);return <article key={m.id} className={`comms-message ${m.sender==='Mara'?'from-mara':m.sender==='Field log'?'field-event':''}`}><header><strong>{m.sender}</strong><span>{t('Chapter','Kapitel')} {m.level+1} · {Math.floor(m.time/60).toString().padStart(2,'0')}:{Math.floor(m.time%60).toString().padStart(2,'0')}</span></header>{m.voiceId&&RADIO[m.voiceId as RadioCue]&&<h3>{RADIO[m.voiceId as RadioCue].title}</h3>}<p>{m.text}</p>{m.voiceId&&<button className="comms-play" onClick={()=>active?onStop():onReplay(m.voiceId)} aria-label={(active?t('Stop','Stoppen'):t('Listen','Anhören'))+': '+m.sender}>{active?<Square size={16}/>:<Play size={16}/>}<span>{active?(status.loading?t('Loading audio…','Ton wird geladen…'):t('Stop playback','Wiedergabe stoppen')):t('Listen to message','Nachricht anhören')}</span><span className="comms-wave" aria-hidden="true">{[7,13,9,19,11,16,6,12].map((height,i)=><i style={{height}} key={i}/>)}</span></button>}</article>})}</div>}
  {tab==='missions'&&<div className="comms-mission"><small>{t('CURRENT MISSION','AKTUELLE MISSION')}</small><h3>{game.data.name}</h3><ul>{game.data.goals.map((goal:string,i:number)=><li key={i} className={game.objectives()[i]?'done':''}><span aria-hidden="true">{game.objectives()[i]?'✓':'○'}</span><span>{goal}</span></li>)}</ul><p>{game.data.hint}</p></div>}
  {tab==='videos'&&<div className="comms-videos"><p>{t('Replay unlocked cinematics. Your mission stays paused.','Sieh freigeschaltete Zwischensequenzen erneut an. Deine Mission bleibt pausiert.')}</p>{films.length===0?<p>{t('Watched films will appear here.','Angesehene Filme erscheinen hier.')}</p>:<div className="comms-film-grid">{films.map(f=><button key={f.id} className="comms-film" onClick={()=>onFilm(f.id as 'intro'|'evac')}><div className="comms-film-image"><img src={ART.sectors[f.id==='evac'?2:0].src} alt=""/><span><Play size={25}/></span></div><div className="comms-film-copy"><small>{t('Chapter','Kapitel')} {f.chapter} · English audio</small><strong>{de?f.deTitle:f.title}</strong><span>{t('Watch again','Erneut ansehen')} →</span></div></button>)}</div>}</div>}
  {tab==='audio'&&<div className="comms-audio"><button className="secondary-btn" onClick={onToggle}>{enabled?<Volume2 size={17}/>:<VolumeX size={17}/>} {enabled?t('Sound on · mute','Ton an · stummschalten'):t('Enable sound','Ton einschalten')}</button><label>{t('Ambient music','Hintergrundmusik')}<output>{Math.round(music*100)}%</output><input type="range" min="0" max="1" step=".01" value={music} onChange={e=>onLevels(Number(e.target.value),voice)}/></label><label>{t('Radio voice','Funkstimmen')}<output>{Math.round(voice*100)}%</output><input type="range" min="0" max="1" step=".01" value={voice} onChange={e=>onLevels(music,Number(e.target.value))}/></label>{call&&<div><small>{t('LAST TRANSMISSION','LETZTER FUNKSPRUCH')}</small><h3>{call.title}</h3><button className="secondary-btn" onClick={()=>onReplay(current)}><Play size={16}/>{t('Play radio call','Funkspruch anhören')}</button>{(status.playing||status.loading)&&<button className="secondary-btn" onClick={onStop}><Square size={14}/>{t('Stop','Stoppen')}</button>}</div>}</div>}
  {status.error&&<p className="audio-error" role="status">{status.error}</p>}
 </section></Localized>;
}
