import {Game,ITEMS,LEVELS} from './engine.mjs';
export const SAVE_KEY='ashfall-save-v1';
const fields=['evacuation','level','unlocked','equipment','inventory','health','kills','totalTime','messages','history','entries','entities','zombies','player','time','signal','spawned','generatorOn','sneak','noise','companion','tutorialDefault','tutorialEnabled','tutorial','lastRadio'];
export function createSave(game){const state={};for(const key of fields)state[key]=game[key];state.mode=['briefing','complete','won','dead'].includes(game.mode)?game.mode:'paused';return JSON.stringify({version:1,savedAt:new Date().toISOString(),state});}
export function readSave(raw){
 if(typeof raw!=='string'||raw.length>4000000)throw Error('Invalid save');const save=JSON.parse(raw),s=save?.state;
 if(save.version!==1||!s||!Number.isInteger(s.level)||!LEVELS[s.level]||!Number.isFinite(s.health)||s.health<0||s.health>100||!['briefing','paused','complete','won','dead'].includes(s.mode))throw Error('Invalid save');
 const items=a=>Array.isArray(a)&&a.every(id=>typeof id==='string'&&ITEMS[id]);const actor=a=>a&&Number.isFinite(a.x)&&Number.isFinite(a.y)&&Math.abs(a.x)<100&&Math.abs(a.y)<100;
 if(!items(s.inventory)||!s.equipment||!['hand','body','head'].every(k=>s.equipment[k]===null||ITEMS[s.equipment[k]]?.slot===k&&s.inventory.includes(s.equipment[k]))||!actor(s.player)||!actor(s.companion)||!Array.isArray(s.entities)||!s.entities.every(e=>actor(e)&&typeof e.id==='string'&&(!e.contents||items(e.contents)))||!Array.isArray(s.zombies)||!s.zombies.every(z=>actor(z)&&Number.isFinite(z.hp))||!Array.isArray(s.messages)||!s.messages.every(m=>typeof m.text==='string')||!Array.isArray(s.history)||!s.tutorial?.facts||!Array.isArray(s.entries)||!s.entries[s.level]||!s.entries.every(e=>!e||items(e.inventory)&&e.equipment&&Number.isFinite(e.health))||!['time','totalTime','kills','spawned','signal','noise','unlocked'].every(k=>Number.isFinite(s[k])))throw Error('Invalid save');return save;
}
export function restoreSave(game,raw){const {state:s}=readSave(raw),candidate=new Game();for(const key of fields)candidate[key]=s[key];candidate.data=LEVELS[s.level];candidate.mode=[2,6].includes(s.level)&&s.mode==='won'?'complete':s.mode;candidate.evacuation=s.evacuation||0;candidate.path=[];candidate.target=null;candidate.selected=null;candidate.effects=[];candidate.companion.path=[];candidate.companion.repath=0;candidate.companion.care=null;candidate.companionOpen=false;candidate.inventoryOpen=false;candidate.lootOpen=false;candidate.inventoryReturnMode=null;candidate.lootContainerId=null;candidate.throwing=false;candidate.flash=0;candidate.pulse=0;
 const listeners=game.listeners,language=game.language;Object.assign(game,candidate);game.listeners=listeners;game.language=language;game.emit();return game;
}
